services:
  
  app:
    build: .
    container_name: library_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5050

  db:
    image: postgres:15
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
