[project]
name = "fastapi-2"
version = "0.1.0"
description = "FastAPI library api"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "motor>=3.7.1",
    "pydantic-mongo>=3.1.0",
    "pymongo>=4.13.0",
]
